discard retry only failed test (#265)
* add test workflow

* discard retry only failed test

* 재시도 로직 트리거 안되는 버그 픽스

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -26,57 +26,32 @@ jobs:
                 -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
                 -quiet
 
-      - name: Test # 테스트. 첫 실패 시 계속 진행
+      - name: Test
         continue-on-error: true
+        run: |
+            echo "HAS_TEST_FAILURE=0" >> $GITHUB_ENV
+            xcodebuild test-without-building \
+                -project Hackle.xcodeproj \
+                -scheme Hackle-Package \
+                -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
+                -retry-tests-on-failure \
+                -test-iterations 3 \
+                -parallel-testing-enabled NO \
+                -resultBundlePath TestResults \
+                -quiet || echo "HAS_TEST_FAILURE=1" >> $GITHUB_ENV
+                
+      - name: Retry when failed # 실패 시 명시적으로 다시 시도
+        if: ${{ env.HAS_TEST_FAILURE == '1' }}
         run: |
             xcodebuild test-without-building \
                 -project Hackle.xcodeproj \
                 -scheme Hackle-Package \
                 -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
                 -retry-tests-on-failure \
-                -test-iterations 2 \
+                -test-iterations 3 \
                 -parallel-testing-enabled NO \
-                -resultBundlePath InitialResults \
+                -resultBundlePath TestResults \
                 -quiet
-                
-      - name: Extract Failed Tests # 실패 테스트 식별 (jq 기본 설치 활용)
-        if: ${{ failure() }}
-        run: |
-          FAILED_TESTS=$(xcrun xcresulttool get --path InitialResults.xcresult --format json |
-            jq -r '
-              [.. | 
-              select(.testStatus? == "Failure") |
-              .identifier._value // empty] |
-              join(",")
-          ')
-          
-          echo "FAILED_TESTS=$FAILED_TESTS" >> $GITHUB_ENV
-          echo "Failed tests: $FAILED_TESTS"
-    
-      - name: Retry when failed # 2번째에서 1번 더 실행
-        if: ${{ failure() && env.FAILED_TESTS != '' }}
-        run: |
-          xcodebuild test-without-building \
-              -project Hackle.xcodeproj \
-              -scheme Hackle-Package \
-              -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
-              -only-testing:"${{ env.FAILED_TESTS }}" \
-              -retry-tests-on-failure \
-              -test-iterations 2 \
-              -resultBundlePath RetryResults \
-              -quiet
-              
-      - name: Merge Results # 결과 병합
-        if: always()
-        run: |
-          if [ -f RetryResults.xcresult ]; then
-            xcrun xcresulttool merge \
-                InitialResults.xcresult \
-                RetryResults.xcresult \
-                --output-path TestResults.xcresult
-          else
-            cp -R InitialResults.xcresult TestResults.xcresult
-          fi
 
       - uses: kishikawakatsumi/xcresulttool@v1
         name: Test Result
